import { Router } from 'express';
import { authRequired } from '../middleware/auth.js';
import authRouter from './auth.js';
import itemsRouter from './items.js';
import importRouter from './import.js';
import stockRouter from './stock.js';
import transactionsRouter from './transactions.js';
import reportsRouter from './reports.js';
import palletsRouter from './pallets.js';
import ordersRouter from './orders.js';
import settingsRouter from './settings.js';
import importLogsRouter from './importLogs.js';
import itemGroupsRouter from './itemGroups.js';
import warehousesRouter from './warehouses.js';
import shipmentsRouter from './shipments.js';
import warehouseStockRouter from './warehouseStock.js';
import onProcessRouter from './onProcess.js';
import palletInventoryRouter from './palletInventory.js';
import usersRouter from './users.js';

const router = Router();
router.use('/auth', authRouter);
router.use('/items', authRequired, itemsRouter);
router.use('/items/import', authRequired, importRouter);
router.use('/stock', authRequired, stockRouter);
router.use('/transactions', authRequired, transactionsRouter);
router.use('/reports', authRequired, reportsRouter);
router.use('/pallets', authRequired, palletsRouter);
router.use('/orders', authRequired, ordersRouter);
router.use('/settings', authRequired, settingsRouter);
router.use('/import-logs', authRequired, importLogsRouter);
router.use('/item-groups', authRequired, itemGroupsRouter);
router.use('/warehouses', authRequired, warehousesRouter);
router.use('/shipments', authRequired, shipmentsRouter);
router.use('/warehouse-stock', authRequired, warehouseStockRouter);
router.use('/on-process', authRequired, onProcessRouter);
router.use('/pallet-inventory', authRequired, palletInventoryRouter);
router.use('/users', authRequired, usersRouter);

export default router;
